apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: insights-operator-IT-run
spec:
  pipelineRef:
    name: insights-operator-IT
  workspaces:
    - name: test-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
